image: golang:latest

stages:
    - benchmarks
    - unit_tests
    
benchmarks:
    stage: benchmarks
    script:
        -  go test -bench=. -benchmem ./...
        
unit_tests:
    stage: unit_tests
    script:
        - go test ./...