image: golang:latest

before_script:
    - go version

stages:
    - tests
    - tests
    
benchmarks:
    stage: tests
    script:
        -  go test -bench=. -benchmem ./...
        
unit_tests:
    stage: tests
    script:
        - go test ./...