package FiatShamirProtocol

const (
	COMMAND_GET_N = "GET_N"
	COMMAND_GET_X = "GET_X"
	COMMAND_GET_E = "GET_E"
	COMMAND_GET_Y = "GET_Y"
	COMMAND_GET_V = "GET_V"
	COMMAND_SERVER_GET_V = "SERVER GET V"
	COMMAND_ANSWER_CODE_SUCCESS = "SUCCESS"
	COMMAND_ANSWER_CODE_ERROR = "ERROR"
)
